// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSSJE71BjS4QdG4Qebq51PXfUG6z30hsg',
    appId: '1:104261438084:web:0ff8fd93618f71f24450d1',
    messagingSenderId: '104261438084',
    projectId: 'opii-7b46b',
    authDomain: 'opii-7b46b.firebaseapp.com',
    storageBucket: 'opii-7b46b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSzwcY9EZegwDji6IWGrcKK5_ZjeFUI0',
    appId: '1:104261438084:android:e76324d9474ef4794450d1',
    messagingSenderId: '104261438084',
    projectId: 'opii-7b46b',
    storageBucket: 'opii-7b46b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoMiFAvkCoz_8-5OLzs56X-s70BEQo8qw',
    appId: '1:104261438084:ios:7c4352d889a4de0d4450d1',
    messagingSenderId: '104261438084',
    projectId: 'opii-7b46b',
    storageBucket: 'opii-7b46b.appspot.com',
    iosClientId: '104261438084-ldp7fobee1465jsqrr8k8ncrhi85c0ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoMiFAvkCoz_8-5OLzs56X-s70BEQo8qw',
    appId: '1:104261438084:ios:61c5603a610f20224450d1',
    messagingSenderId: '104261438084',
    projectId: 'opii-7b46b',
    storageBucket: 'opii-7b46b.appspot.com',
    iosClientId: '104261438084-0e37kb7sj2mrggp9s0ian5tvpt6r9b16.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestock.RunnerTests',
  );
}
